"""Create the durable permanent-purge re-authentication schema foundation.

This revision creates only durable schema state. It does not verify passwords,
issue or consume nonces, change routes, or invoke purge execution.
"""

from sqlalchemy import inspect, text


revision = "0008_durable_purge_reauth_state"
down_revision = "0007_permanent_purge_workflow"
branch_labels = None
depends_on = None
message = "Add durable permanent-purge re-authentication state"


AUTHORIZATION_TABLE = "workspace_purge_execution_authorizations"
THROTTLE_TABLE = "workspace_purge_reauth_actor_throttles"
AUTHORIZATION_STATES = (
    "ACTIVE",
    "CLAIMED",
    "SERVICE_STARTED",
    "CONSUMED_SUCCESS",
    "REVOKED",
    "CLAIMED_UNRESOLVED",
)


def _is_pg(connection):
    return connection.dialect.name == "postgresql"


def _has_table(connection, table_name):
    return inspect(connection).has_table(table_name)


def _columns(connection, table_name):
    return tuple(column["name"] for column in inspect(connection).get_columns(table_name))


def _has_column(connection, table_name, column_name):
    return column_name in _columns(connection, table_name)


def _quoted_values(values):
    return ", ".join("'" + value.replace("'", "''") + "'" for value in values)


def _hash_check(connection, column_name):
    if _is_pg(connection):
        return f"{column_name} IS NULL OR {column_name} ~ '^[0-9a-f]{{64}}$'"
    return f"{column_name} IS NULL OR (length({column_name}) = 64 AND {column_name} NOT GLOB '*[^0-9a-f]*')"


def _authorization_state_check():
    state = "state"
    common = (
        "authenticated_at IS NOT NULL AND expires_at IS NOT NULL "
        "AND nonce_hash IS NULL"
    )
    return f"""
        (state = 'ACTIVE' AND nonce_hash IS NOT NULL
            AND authenticated_at IS NOT NULL AND expires_at IS NOT NULL
            AND consumed_at IS NULL AND claimed_at IS NULL
            AND service_started_at IS NULL AND execution_started_event_id IS NULL
            AND revoked_at IS NULL AND revocation_reason IS NULL)
        OR
        (state = 'CLAIMED' AND {common}
            AND consumed_at IS NOT NULL AND claimed_at IS NOT NULL
            AND service_started_at IS NULL AND execution_started_event_id IS NULL
            AND revoked_at IS NULL)
        OR
        (state = 'CLAIMED_UNRESOLVED' AND {common}
            AND consumed_at IS NOT NULL AND claimed_at IS NOT NULL
            AND service_started_at IS NULL AND execution_started_event_id IS NULL
            AND revoked_at IS NULL)
        OR
        (state = 'SERVICE_STARTED' AND {common}
            AND consumed_at IS NOT NULL AND claimed_at IS NOT NULL
            AND service_started_at IS NOT NULL
            AND execution_started_event_id IS NOT NULL AND revoked_at IS NULL)
        OR
        (state = 'CONSUMED_SUCCESS' AND {common}
            AND consumed_at IS NOT NULL AND claimed_at IS NOT NULL
            AND service_started_at IS NOT NULL
            AND execution_started_event_id IS NOT NULL AND revoked_at IS NULL)
        OR
        (state = 'REVOKED' AND {common}
            AND revoked_at IS NOT NULL AND revocation_reason IS NOT NULL
            AND service_started_at IS NULL AND execution_started_event_id IS NULL
            AND ((consumed_at IS NULL AND claimed_at IS NULL)
                 OR (consumed_at IS NOT NULL AND claimed_at IS NOT NULL)))
    """


def _create_authorization_table(connection):
    if _has_table(connection, AUTHORIZATION_TABLE):
        raise RuntimeError("0008 authorization table already exists; refusing ambiguous upgrade.")
    if not _has_table(connection, "workspace_purge_requests") or not _has_table(connection, "users"):
        raise RuntimeError("0008 requires existing purge requests and users tables.")
    if not _has_table(connection, "purge_lifecycle_events"):
        raise RuntimeError("0008 requires the existing purge lifecycle events table.")

    connection.execute(
        text(
            f"""
            CREATE TABLE {AUTHORIZATION_TABLE} (
                id INTEGER PRIMARY KEY{' GENERATED BY DEFAULT AS IDENTITY' if _is_pg(connection) else ' AUTOINCREMENT'},
                purge_request_id INTEGER NOT NULL REFERENCES workspace_purge_requests(id) ON DELETE RESTRICT,
                actor_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                method VARCHAR(30) NOT NULL DEFAULT 'local_password',
                generation INTEGER NOT NULL DEFAULT 1,
                state VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
                nonce_hash VARCHAR(64),
                authenticated_at TIMESTAMP,
                expires_at TIMESTAMP,
                consumed_at TIMESTAMP,
                claimed_at TIMESTAMP,
                service_started_at TIMESTAMP,
                execution_started_event_id INTEGER REFERENCES purge_lifecycle_events(id) ON DELETE RESTRICT,
                revoked_at TIMESTAMP,
                revocation_reason VARCHAR(80),
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_workspace_purge_execution_authorizations_request UNIQUE (purge_request_id),
                CONSTRAINT uq_workspace_purge_execution_authorizations_event_id UNIQUE (execution_started_event_id),
                CONSTRAINT ck_workspace_purge_execution_authorizations_method CHECK (method = 'local_password'),
                CONSTRAINT ck_workspace_purge_execution_authorizations_generation CHECK (generation >= 1),
                CONSTRAINT ck_workspace_purge_execution_authorizations_state CHECK (state IN ({_quoted_values(AUTHORIZATION_STATES)})),
                CONSTRAINT ck_workspace_purge_execution_authorizations_nonce_hash CHECK ({_hash_check(connection, 'nonce_hash')}),
                CONSTRAINT ck_workspace_purge_execution_authorizations_time_order CHECK (
                    expires_at IS NULL OR authenticated_at IS NULL OR expires_at >= authenticated_at
                ),
                CONSTRAINT ck_workspace_purge_execution_authorizations_state_shape CHECK ({_authorization_state_check()})
            )
            """
        )
    )


def _create_throttle_table(connection):
    if _has_table(connection, THROTTLE_TABLE):
        raise RuntimeError("0008 throttle table already exists; refusing ambiguous upgrade.")
    if not _has_table(connection, "users"):
        raise RuntimeError("0008 requires the existing users table.")

    connection.execute(
        text(
            f"""
            CREATE TABLE {THROTTLE_TABLE} (
                actor_user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT,
                failed_attempt_count INTEGER NOT NULL DEFAULT 0,
                first_failed_at TIMESTAMP,
                last_failed_at TIMESTAMP,
                locked_until TIMESTAMP,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_workspace_purge_reauth_actor_throttles_count CHECK (failed_attempt_count >= 0),
                CONSTRAINT ck_workspace_purge_reauth_actor_throttles_empty_shape CHECK (
                    failed_attempt_count <> 0
                    OR (first_failed_at IS NULL AND last_failed_at IS NULL AND locked_until IS NULL)
                ),
                CONSTRAINT ck_workspace_purge_reauth_actor_throttles_failure_shape CHECK (
                    failed_attempt_count = 0
                    OR (first_failed_at IS NOT NULL AND last_failed_at IS NOT NULL)
                ),
                CONSTRAINT ck_workspace_purge_reauth_actor_throttles_time_order CHECK (
                    last_failed_at IS NULL OR first_failed_at IS NULL OR last_failed_at >= first_failed_at
                ),
                CONSTRAINT ck_workspace_purge_reauth_actor_throttles_lock_order CHECK (
                    locked_until IS NULL OR last_failed_at IS NULL OR locked_until >= last_failed_at
                )
            )
            """
        )
    )


def _constraint_names(connection, table_name):
    inspector = inspect(connection)
    names = set()
    names.update(item.get("name") for item in inspector.get_unique_constraints(table_name))
    names.update(item.get("name") for item in inspector.get_check_constraints(table_name))
    names.update(item.get("name") for item in inspector.get_foreign_keys(table_name))
    return {name for name in names if name}


def _index_names(connection, table_name):
    inspector = inspect(connection)
    indexes = {
        item.get("name")
        for item in inspector.get_indexes(table_name)
        if item.get("name")
    }
    if not _is_pg(connection):
        return indexes
    constraint_backed_indexes = {
        row[0]
        for row in connection.execute(
            text(
                """
                SELECT index_class.relname
                FROM pg_class AS table_class
                JOIN pg_namespace AS table_namespace
                  ON table_namespace.oid = table_class.relnamespace
                JOIN pg_index AS index_info
                  ON index_info.indrelid = table_class.oid
                JOIN pg_class AS index_class
                  ON index_class.oid = index_info.indexrelid
                JOIN pg_constraint AS constraint_info
                  ON constraint_info.conindid = index_class.oid
                WHERE table_namespace.nspname = current_schema()
                  AND table_class.relname = :table_name
                  AND constraint_info.contype IN ('p', 'u')
                """
            ),
            {"table_name": table_name},
        )
    }
    return indexes - constraint_backed_indexes


def _verify_foreign_keys(connection):
    inspector = inspect(connection)
    def _ondelete(item):
        # SQLite's SQLAlchemy inspector omits the default RESTRICT action;
        # PostgreSQL reports the explicit action from the catalog.
        return (item.get("options") or {}).get("ondelete") or ("RESTRICT" if not _is_pg(connection) else None)

    authorization_fks = {
        (tuple(item["constrained_columns"]), item["referred_table"], tuple(item["referred_columns"]), _ondelete(item))
        for item in inspector.get_foreign_keys(AUTHORIZATION_TABLE)
    }
    expected_authorization_fks = {
        (("purge_request_id",), "workspace_purge_requests", ("id",), "RESTRICT"),
        (("actor_user_id",), "users", ("id",), "RESTRICT"),
        (("execution_started_event_id",), "purge_lifecycle_events", ("id",), "RESTRICT"),
    }
    if authorization_fks != expected_authorization_fks:
        raise RuntimeError("0008 authorization foreign-key contract mismatch.")

    throttle_fks = {
        (tuple(item["constrained_columns"]), item["referred_table"], tuple(item["referred_columns"]), _ondelete(item))
        for item in inspector.get_foreign_keys(THROTTLE_TABLE)
    }
    if throttle_fks != {(("actor_user_id",), "users", ("id",), "RESTRICT")}:
        raise RuntimeError("0008 throttle foreign-key contract mismatch.")


def verify_upgrade(connection):
    expected_authorization_columns = (
        "id", "purge_request_id", "actor_user_id", "method", "generation", "state",
        "nonce_hash", "authenticated_at", "expires_at", "consumed_at", "claimed_at",
        "service_started_at", "execution_started_event_id", "revoked_at", "revocation_reason",
        "created_at", "updated_at",
    )
    expected_throttle_columns = (
        "actor_user_id", "failed_attempt_count", "first_failed_at", "last_failed_at",
        "locked_until", "created_at", "updated_at",
    )
    if _columns(connection, AUTHORIZATION_TABLE) != expected_authorization_columns:
        raise RuntimeError("0008 authorization column contract mismatch.")
    if _columns(connection, THROTTLE_TABLE) != expected_throttle_columns:
        raise RuntimeError("0008 throttle column contract mismatch.")
    if "workspace_id" in _columns(connection, AUTHORIZATION_TABLE) or "workspace_id" in _columns(connection, THROTTLE_TABLE):
        raise RuntimeError("0008 must not duplicate workspace_id in re-auth tables.")
    _verify_foreign_keys(connection)
    required_authorization_constraints = {
        "uq_workspace_purge_execution_authorizations_request",
        "uq_workspace_purge_execution_authorizations_event_id",
        "ck_workspace_purge_execution_authorizations_method",
        "ck_workspace_purge_execution_authorizations_generation",
        "ck_workspace_purge_execution_authorizations_state",
        "ck_workspace_purge_execution_authorizations_nonce_hash",
        "ck_workspace_purge_execution_authorizations_time_order",
        "ck_workspace_purge_execution_authorizations_state_shape",
    }
    if not required_authorization_constraints.issubset(_constraint_names(connection, AUTHORIZATION_TABLE)):
        raise RuntimeError("0008 authorization constraint contract mismatch.")
    required_throttle_constraints = {
        "ck_workspace_purge_reauth_actor_throttles_count",
        "ck_workspace_purge_reauth_actor_throttles_empty_shape",
        "ck_workspace_purge_reauth_actor_throttles_failure_shape",
        "ck_workspace_purge_reauth_actor_throttles_time_order",
        "ck_workspace_purge_reauth_actor_throttles_lock_order",
    }
    if not required_throttle_constraints.issubset(_constraint_names(connection, THROTTLE_TABLE)):
        raise RuntimeError("0008 throttle constraint contract mismatch.")
    if _index_names(connection, AUTHORIZATION_TABLE) or _index_names(connection, THROTTLE_TABLE):
        raise RuntimeError("0008 has unexpected redundant indexes.")
    for table_name in (AUTHORIZATION_TABLE, THROTTLE_TABLE):
        if connection.execute(text(f"SELECT 1 FROM {table_name} LIMIT 1")).fetchone() is not None:
            raise RuntimeError("0008 migration tables must start empty.")


def verify_downgrade(connection):
    if _has_table(connection, AUTHORIZATION_TABLE) or _has_table(connection, THROTTLE_TABLE):
        raise RuntimeError("0008 downgrade did not remove both re-auth tables.")


def upgrade():
    from extensions import db

    with db.engine.begin() as connection:
        if _has_table(connection, AUTHORIZATION_TABLE) or _has_table(connection, THROTTLE_TABLE):
            raise RuntimeError("0008 target tables already exist; refusing ambiguous upgrade.")
        _create_authorization_table(connection)
        _create_throttle_table(connection)
        verify_upgrade(connection)


def downgrade():
    from extensions import db

    with db.engine.begin() as connection:
        for table_name in (AUTHORIZATION_TABLE, THROTTLE_TABLE):
            if _has_table(connection, table_name) and connection.execute(text(f"SELECT 1 FROM {table_name} LIMIT 1")).fetchone() is not None:
                raise RuntimeError("0008 downgrade requires both re-auth tables to be empty.")
        if _has_table(connection, THROTTLE_TABLE):
            connection.execute(text(f"DROP TABLE {THROTTLE_TABLE}"))
        if _has_table(connection, AUTHORIZATION_TABLE):
            connection.execute(text(f"DROP TABLE {AUTHORIZATION_TABLE}"))
        verify_downgrade(connection)
